### ISSUE TITLE
Špatná hodnota - Siton výroba

### ISSUE THREAD

**Issue by tomV81** [TataGEEK/Siton210#1]
Špatně načítá výrobu. Stav výroby na displeji 446,46 kWh, načítaná hodnota výroby 53269 Wh a 0,006 kWh.

**Comment by tomV81** [comment]
Stačí opravit čtení senzoru výroby. Je nutné číst 2 registry (Lo jako první):
    
    - platform: modbus_controller
      modbus_controller_id: siton210
      id: vyroba
      name: "${node_name} Výroba kWh"
      state_class: total_increasing
      device_class: energy
      address: 0x000C
      unit_of_measurement: "kWh"
      icon: mdi:chart-bell-curve-cumulative
      register_type: holding
      value_type: U_DWORD_R
      accuracy_decimals: 3
      filters:
        - multiply: 0.001

**Comment by TataGEEK** [comment]
Výrobu zatím nemám jak otestovat a ve vloženém kódu máš adresu 0x000C označenou jako kWh, i když by měla být jen Wh. 

Výroba v Wh (adresa 0x000C) je tedy U_DWORD_R ?
Výroba v kWk (adresa 0x000D) zůstává U_WORD ?

**Comment by tomV81** [comment]
Výroba je jen jedna, ale hodnota zabírá 2 registry. Musí být tedy `value_type: U_DWORD_R`. Takto dostaneš správnou hodnotu a tím, že na ní uděláš `multiply: 0.001`, máš hodnotu v kWh na 3 desetiny.
Ta druhá část, kterou máš jako Výroba kWh od `address: 0x000D` se vůbec nepoužije.
Takto mě sedí výroba s displejem.

**Comment by TataGEEK** [comment]
Díky za opravu, kód změněn.
